### ISSUE TITLE
Spell chariot of ice cause server crash

### ISSUE THREAD

**Issue by TUsama** [Electroblob77/TF-Spell-Pack#7]
https://paste.ubuntu.com/p/gwSZ9NTqpS/ 
I dont't know if it is the same bug(#3 ), but somebody send me this crash-report which happened in sever.

**Comment by Electroblob77** [comment]
That's a different crash report to the other issue, it may be that the user who posted the other issue gave me the wrong report because I haven't been able to recreate it, or it may be a different problem. Either way, I can see what's gone wrong in your crash report and I should be able to fix it fairly easily. Thanks for reporting.

**Comment by shell84** [comment]
Also crashing out whenever I try to use this spell on my server. Not a server crash and my game doesn't crash completely. Just get chucked out with a internal server error, can then log back in and the spell is a mystery again.

**Comment by WolfBV** [comment]
Experiencing this while playing the MCEternal modpack, can prolly use that as a start to figure out which mods, if any, are causing this crash-to-main-menu issue.

**Comment by shell84** [comment]
yeah mc eternal full version for me too
